service: jo-innovation

provider:
    name: aws
    runtime: python3.9
    profile: default

plugins:
    - serverless-offline


package:
    individually: true

functions:
    hello:
        handler: lambdas/test.lambda_handler
        events:
            - http:
                  path: sales-invoice/services/apexrest/JobOptimization/
                  method: GET
                  cors: true

resources:
    Resources:
        DemoBucketUpload:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: jo-innovation-demo-bucket